### ISSUE TITLE
 can you release a version?

### ISSUE THREAD

**Issue by AllenX2018** [asynkron/protoactor-go#438] opened 2020-12-30 08:47 UTC
Hello ~ community maintainer:
the community has not released a version for a long time, can you release a version?

**Comment by cupen** [comment] 2020-12-30 15:08
Hello. 
Duplicate of  #307 .

However, I recommand you just use `go module`.
```
export GO111MODULE=on
go get -u github.com/AsynkronIT/protoactor-go@commit_id
```

**Comment by AllenX2018** [comment] 2020-12-31 08:08
@cupen 
Thank you very much for your answer, I use `go module`, but the company has requirements for the version

**Comment by cupen** [comment] 2021-01-04 04:25
@AllenX2018 That's OK. You can get a generated version like `v0.0.0-${git-commit-id}`.
If you want take control, just make a fork of this repo. That's what I did. 
Here is a snippet of my `go.mod`.
```
replace (
	github.com/AsynkronIT/protoactor-go => github.com/cupen/protoactor-go v0.0.0-xxxxxxxxxx
)

require (
	github.com/AsynkronIT/protoactor-go v0.0.0-20200729120717-be0cc59aab76
)
```

**Comment by Menniti** [comment] 2021-08-06 22:18
Hey I would like to use this in my company also.... but without version is hard to propose it to then.
Please let me know if the project still alive, this is absolutely brilliant cannot be forget! 
Thank youu

**Closed as completed** 2022-04-05 14:21 UTC
