### ISSUE TITLE
Support opentelemetry

### ISSUE THREAD

**Issue by acroca** [asynkron/protoactor-go#466] opened 2021-03-31 21:58 UTC
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
I use opentelemetry in my project and I think it'd be better if protoactor had a middleware built in.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by rogeralsing** [comment] 2021-04-27 17:42
Adding this to the roadmap

**Comment by rogeralsing** [comment] 2021-08-15 14:43
Closing as duplicate of #477

**Closed as completed by rogeralsing** 2021-08-15 14:43 UTC
Labels: 1. triaged
